config/routes.rb
Rails.application.routes.draw do

  resources :actors
  resources :movies
  resources :genres

  get "about" => "site#about"

  root 'site#home'
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :movies, dependent: :destroy

  def self.search(search)
    Actor.where("name LIKE ?", "%#{search}%")
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :movies
end

app/models/genres_movies.rb
class GenresMovies < ActiveRecord::Base
  belongs_to :genre
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :actor
  has_and_belongs_to_many :genres

 def self.search(search)
   Movie.where("title LIKE ?", "%#{search}%")
 end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all.sort_by { |actor| actor.name }
    if params[:search]
      @actors = Actor.search(params[:search])
    else
      @actors = Actor.all.sort_by { |actor| actor.name }
    end
  end

  def show
    @actor = Actor.find( params[:id] )
  end

  def new
    @actor = Actor.new
  end

  def create
    actor = Actor.new( actor_params )

    if actor.save
      redirect_to actors_path
    else
      render 'new'
    end
  end

  def edit
    @actor = Actor.find( params[:id] )
  end

  def update
    @actor = Actor.find( params[:id] )

    if @actor.update_attributes( actor_params )
      redirect_to @actor
    else
      render 'edit'
    end
  end

  def destroy
    @actor = Actor.find( params[:id] )

    @actor.destroy

    redirect_to actors_path
  end

private

  def actor_params
    params.require( :actor ).permit( :name, :age, :country, :bio )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.sort_by { |genre| genre.movies.size }.reverse
  end

  def show
    @genre = Genre.find( params[:id] )
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    if params[:search]
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all.sort_by { |movie| movie.year }
    end
  end

  def show
    @movie = Movie.find( params[:id] )
  end

  def new
    @movie = Movie.new
    @movie.actor_id = params[:actor_id]
  end

  def create
    movie = Movie.new( movie_params )
    if movie.save
      redirect_to actor_path( movie.actor_id )
    else
      render new_movie_path
    end
  end

  def edit
    @movie = Movie.find( params[:id] )
  end

  def update
    @movie = Movie.find( params[:id] )

    if @movie.update_attributes( movie_params )
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find( params[:id] )

    actor_id = @movie.actor_id

    @movie.destroy

    redirect_to actor_path( actor_id )
  end

  private

  def movie_params
    params.require( :movie ).permit( :title, :year, :cover, :plot, :actor_id, genre_ids: [] )
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/actors/_actor.html.erb
<div class="actor-item">
   <div class="inline details">
     <p><%= link_to actor.name, actor %></p>
      <p><%= actor.age %></p>
      <p><%= actor.country %></p>
      <p><%= actor.bio %></p>
   </div>
</div>

app/views/actors/_form.html.erb
<%= form_for @actor do |f| %>

    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control", placeholder: ". . ." %>
    </div>

    <div class="form-group">
       <%= f.label :age %>
       <%= f.text_field :age, class: "form-control", placeholder: ". . ."   %>
    </div>

    <div class="form-group">
       <%= f.label :country %>
       <%= f.text_field :country, class: "form-control", placeholder: ". . ."   %>
    </div>

    <div class="form-group">
       <%= f.label :bio %>
       <%= f.text_area :bio, class: "form-control", rows: 10, placeholder: ". . ."  %>
    </div>

    <%= f.submit (@actor.new_record? ? "Create" : "Update"), class: "form-control btn-success" %>

<% end %>

app/views/actors/edit.html.erb
<h1>Edit Actor</h1>

<%= render "form" %>

app/views/actors/index.html.erb
<h1>Actors</h1>

  <%= form_tag(actors_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Actors" %>
  <%= submit_tag "Search" %>
  <% end %>

  <% if @actors.present? %>
    <%= render @actors %>
  <% else %>
    <p>There are no actors with the name <%= params[:search] %>.</p>
  <% end %>

app/views/actors/new.html.erb
<H1>New Actor</H1>

<%= render "form" %>

app/views/actors/show.html.erb
<h1>
  <%= @actor.name %>
  <%= link_to "Delete", actor_path( @actor ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", style: "float: right" %>
  <%= link_to "Edit", edit_actor_path( @actor ), class: "btn btn-warning", style: "float: right" %>
</h1>

<H3> Age: <%= @actor.age %></H3>
<H3> Country: <%= @actor.country %></H3>
<p> <%= simple_format @actor.bio %></p>

<h2>Movies</h2>

<%= link_to "Add new movie", new_movie_path( actor_id: @actor.id ), class: "btn btn-success", style: "float: right" %>

<% movies = @actor.movies.sort_by { |movie| movie.year } %>
<%= render movies, hide_actor: true %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<div>
  <% @genres.each do |genre| %>
    <%= link_to "#{genre.name} • #{genre.movies.size}", genre, class: "btn btn-primary" %>
   <% end %>
</div>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<%= render @genre.movies %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Actors", actors_path %></li>
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to "Genres", genres_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Novad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main" class="container-fluid">
     <%= render "layouts/nav" %>

     <%= yield %>

  </div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <%= f.hidden_field :actor_id, :value => @movie.actor.id%>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: ". . ." %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: "form-control", placeholder: ". . ." %>
  </div>

  <div class="form-group">
    <%= f.label :cover %>
    <%= f.text_field :cover, class: "form-control", placeholder: ". . ." %>
  </div>

  <div class="form-group">
    <%= f.label :plot %>
    <%= f.text_field :plot, class: "form-control", placeholder: ". . ." %>
  </div>

  <div class="form-group">
    <%= f.label :genres, :class => "control-label" %>
    <div>
      <% genres = Genre.all.map {|t| [t.name, t.id]}.sort %>
      <%= f.select :genre_ids, genres, {class: "form-control", prompt: true}, { multiple: true, size: 10 } %>
      <p class="help-block">Select multiple with ctrl</p>
    </div>
  </div>

  <%= f.submit (@movie.new_record? ? "Create" : "Update"), class: "form-control btn-primary" %>

<% end %>

app/views/movies/_movie.html.erb
<div class="movie-item">

   <div class="inline cover">
      <img class="small-cover" src="<%= movie.cover %>"/>
   </div>

   <div class="inline details">

      <h3><%= link_to movie.title, movie %></h3>

      <% if !defined?(hide_actor) || !hide_actor %>
        <h4><%= link_to movie.actor.name, movie.actor %></h4>
      <% end %>

      <p><%= movie.year %></p>
      <p><%= movie.plot %></p>

      <p>
         <% movie.genres.each do |genre| %>
             <%= link_to "#{genre.name}", genre, class: "btn btn-primary btn-xs" %>
         <% end %>
      </p>

   </div>

</div>

app/views/movies/edit.html.erb
<h1>Edit movie by <%= @movie.actor.name %></h1>

<%= render "form" %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<%= form_tag(movies_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Movies" %>
<%= submit_tag "Search" %>
<% end %>

<% if @movies.present? %>
  <%= render @movies %>
<% else %>
  <p>There are no movie titles containing the term(s) <%= params[:search] %>.</p>
<% end %>

<!-- <%= render @movies %> -->

app/views/movies/new.html.erb
<h1>New Movie by <%= @movie.actor.name %></h1>

<%= render "form" %>

app/views/movies/show.html.erb
<h1>
  <%= @movie.title %>
  <%= link_to "Delete", movie_path( @movie ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default", style: "float: right" %>
  <%= link_to "Edit", edit_movie_path( @movie ), class: "btn btn-default", style: "float: right" %>
 </h1>

<h3><%= link_to @movie.actor.name, @movie.actor %> </h3>

<p><%= @movie.year %></p>
<p><%= @movie.plot %></p>

<p>
   <% @movie.genres.each do |genre| %>
       <%= link_to "#{genre.name}", genre, class: "btn btn-primary btn-xs" %>
   <% end %>
</p>

<img class="cover" src="<%= @movie.cover %>"/>

app/views/site/about.html.erb
<h1>Novad</h1>

<p>Celebrating culture with Movies by Actors.</p>

app/views/site/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Novad</h1>
    <div class="btn-group btn-group-justified">
      <a href="<%= actors_path %>" class="btn btn-primary"><h2>Actors</h2></a>
      <a href="<%= movies_path %>" class="btn btn-danger"><h2>Movies</h2></a>
      <a href="<%= genres_path %>" class="btn btn-success"><h2>Genres</h2></a>
    </div>
    <hr />
    <p>The most popular tool to check out the latest movies! Keep track of what your favorite actor is up to!</p>
  </div>
</div>

<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://vignette3.wikia.nocookie.net/lotr/images/7/74/LOTRFOTRmovie.jpg/revision/latest?cb=20150203040819" alt="LOTR1" width="460" height="345">
      </div>

      <div class="item">
        <img src="https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg" alt="Chania" width="460" height="345">
      </div>

      <div class="item">
        <img src="https://upload.wikimedia.org/wikipedia/en/0/07/The_Good_Son_(movie_poster).jpg" alt="Flower" width="460" height="345">
      </div>

      <div class="item">
        <img src="https://i.jeded.com/i/pirates-of-the-caribbean-1-the-curse-of-the-black-pearl.12323.jpg" alt="Flower" width="460" height="345">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>